/**
 * @file thello.cc
 */

#include <stdio.h>
#include "thello-version.h"  // generated by cmake

int main(int argc, char **argv)
{
  printf("Hello, world -- thello version %s.%s.%s\n",thello_MAJOR,thello_MINOR,thello_MICRO);

  printf("argc %d\n",argc);
  for(int i=0; i<argc; i++)
    {
      printf(" arg[%d] %s\n",i,argv[i]);
    }

  return 0;
}
